spring:
  application:
    name: order_api
  datasource:
    url: jdbc:postgresql://localhost:5455/gestaopedidos
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
#logging:
#  level:
#    root: ERROR
#    org.springframework: ERROR
# OpenApi
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
  version: v1
  show-actuator: false

payment-service:
  name: Payment-Api
  url: http://localhost:8080/api

production-service:
    name: Production-Api
    url: http://localhost:8000/api