spring:
  application:
    name: order_api
  datasource:
    url: jdbc:tc:postgresql:15://localhost/testdb
    username: testuser
    password: testpass
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

# OpenApi
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
  version: v1
  show-actuator: false

