spring:
  application:
    name: order_api
  datasource:
    url: jdbc:postgresql://localhost:5455/gestaopedidos
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
# OpenApi
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
  version: v1
  show-actuator: false

payment-service:
  name: Payment-Api
  url: https://deckofcardsapi.com/api/deck/new/shuffle/?deck_count=1

production-service:
    name: Production-Api
    url: https://deckofcardsapi.com/api/deck/new/shuffle/?deck_count=1