apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestaopedidos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestaopedidos
  template:
    metadata:
      labels:
        app: gestaopedidos
    spec:
      containers:
        - name: gestaopedidos
          image: 264945224125.dkr.ecr.us-east-1.amazonaws.com/gestaopedidos_repository:latest # Imagem local
#          imagePullPolicy: Never # Força o kubernets a não puxar de um repositório remoto
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: gestaopedidos-config
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
