apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gestaopedidos-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gestaopedidos-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
